import os
from dotenv import load_dotenv
load_dotenv()

def _bool(n,d):
    v=os.getenv(n); return d if v is None else v.strip().lower() in ("1","true","yes","on")
def _float(n,d):
    try:return float(os.getenv(n,d))
    except:return d
def _int(n,d):
    try:return int(os.getenv(n,d))
    except:return d

class Config:
    API_KEY=os.getenv("BITGET_API_KEY",""); API_SECRET=os.getenv("BITGET_API_SECRET",""); API_PASSWORD=os.getenv("BITGET_API_PASSWORD","")
    DEMO_MODE=_bool("DEMO_MODE",True); LIVE_TRADING_ENABLED=_bool("LIVE_TRADING_ENABLED",False)
    RISK_PER_TRADE_PERCENT=_float("RISK_PER_TRADE_PERCENT",.50); MAX_CONCURRENT_TRADES=_int("MAX_CONCURRENT_TRADES",3)
    MAX_DAILY_LOSS_PERCENT=_float("MAX_DAILY_LOSS_PERCENT",3); MAX_WEEKLY_LOSS_PERCENT=_float("MAX_WEEKLY_LOSS_PERCENT",6)
    MAX_EQUITY_DRAWDOWN_PERCENT=_float("MAX_EQUITY_DRAWDOWN_PERCENT",10); MAX_MARGIN_PERCENT=_float("MAX_MARGIN_PERCENT",20)
    MAX_LEVERAGE=_int("MAX_LEVERAGE",5); MIN_RISK_REWARD=_float("MIN_RISK_REWARD",2)
    MAX_CORRELATED_EXPOSURE_PERCENT=_float("MAX_CORRELATED_EXPOSURE_PERCENT",2); MAX_DAILY_TRADES=_int("MAX_DAILY_TRADES",8)
    CONSECUTIVE_LOSS_COOLDOWN=_int("CONSECUTIVE_LOSS_COOLDOWN",3)
    QUOTE_CURRENCY=os.getenv("QUOTE_CURRENCY","USDT"); TOP_N_COINS_BY_VOLUME=_int("TOP_N_COINS_BY_VOLUME",20)
    SCAN_WORKERS=_int("SCAN_WORKERS",5); MIN_24H_VOLUME_USDT=_float("MIN_24H_VOLUME_USDT",20_000_000); MAX_SPREAD_BPS=_float("MAX_SPREAD_BPS",20)
    MIN_CONFLUENCE_SCORE=_int("MIN_CONFLUENCE_SCORE",75); VERBOSE_SIGNALS=_bool("VERBOSE_SIGNALS",True)
    TF_BIAS_HTF="1d"; TF_BIAS_MTF="4h"; TF_SETUP="1h"; TF_TRIGGER="15m"
    ATR_PERIOD=_int("ATR_PERIOD",14); MIN_STRUCTURE_CANDLES=_int("MIN_STRUCTURE_CANDLES",80)
    SWING_LEFT=_int("SWING_LEFT",3); SWING_RIGHT=_int("SWING_RIGHT",3); EQUAL_LEVEL_ATR=_float("EQUAL_LEVEL_ATR",.12)
    MIN_DISPLACEMENT_ATR=_float("MIN_DISPLACEMENT_ATR",1.0); DISPLACEMENT_LOOKBACK=_int("DISPLACEMENT_LOOKBACK",8)
    FVG_MIN_ATR=_float("FVG_MIN_ATR",.08); FVG_LOOKBACK=_int("FVG_LOOKBACK",60); OB_LOOKBACK=_int("OB_LOOKBACK",60); OB_SEARCH_BARS=_int("OB_SEARCH_BARS",6)
    LIQUIDITY_LOOKBACK=_int("LIQUIDITY_LOOKBACK",80); LIQUIDITY_LEVELS=_int("LIQUIDITY_LEVELS",8); SWEEP_LOOKBACK=_int("SWEEP_LOOKBACK",12)
    SETUP_MAX_AGE_BARS=_int("SETUP_MAX_AGE_BARS",20); SETUP_NEAR_PCT=_float("SETUP_NEAR_PCT",.006)
    # Horizontal S/R confirmation
    SR_ZONE_ATR=_float("SR_ZONE_ATR",0.25); SR_ZONE_PCT=_float("SR_ZONE_PCT",0.0015)
    SR_MAX_LEVELS=_int("SR_MAX_LEVELS",12); SR_MAX_DISTANCE_PCT=_float("SR_MAX_DISTANCE_PCT",0.012)
    SR_REJECTION_LOOKBACK=_int("SR_REJECTION_LOOKBACK",6); SR_WICK_RATIO=_float("SR_WICK_RATIO",0.35)
    SR_MIN_BODY_RATIO=_float("SR_MIN_BODY_RATIO",0.25); SR_VOLUME_MULTIPLIER=_float("SR_VOLUME_MULTIPLIER",1.10)
    SR_MIN_SCORE=_int("SR_MIN_SCORE",70); SR_REQUIRE_CONFIRMATION=_bool("SR_REQUIRE_CONFIRMATION",True)
    # Price-action confirmation on the 15m execution timeframe.
    PA_REQUIRE_CONFIRMATION=_bool("PA_REQUIRE_CONFIRMATION",True); PA_MIN_SCORE=_int("PA_MIN_SCORE",1); PA_LOOKBACK=_int("PA_LOOKBACK",5)
    SESSION_FILTER_ENABLED=_bool("SESSION_FILTER_ENABLED",True); SESSION_FILTER_MODE=os.getenv("SESSION_FILTER_MODE","execution_only"); LONDON_START_UTC=_int("LONDON_START_UTC",7); LONDON_END_UTC=_int("LONDON_END_UTC",11)
    NEW_YORK_START_UTC=_int("NEW_YORK_START_UTC",13); NEW_YORK_END_UTC=_int("NEW_YORK_END_UTC",17); ALLOW_ASIA=_bool("ALLOW_ASIA",False)
    API_TIMEOUT_MS=_int("API_TIMEOUT_MS",15000); API_RETRIES=_int("API_RETRIES",3); SCAN_INTERVAL_SECONDS=_int("SCAN_INTERVAL_SECONDS",300)
    # Public market ticker calls can be slower than private/account calls.
    MARKET_TICKER_TIMEOUT_MS=_int("MARKET_TICKER_TIMEOUT_MS",30000); TICKER_FETCH_RETRIES=_int("TICKER_FETCH_RETRIES",3)
    TICKER_CACHE_TTL_SECONDS=_int("TICKER_CACHE_TTL_SECONDS",1800); TICKER_CACHE_FILE=os.getenv("TICKER_CACHE_FILE","state/liquid_universe.json")
    BACKTEST_ENTRY_TIMEOUT_BARS=_int("BACKTEST_ENTRY_TIMEOUT_BARS",8); BACKTEST_MAX_HOLD_BARS=_int("BACKTEST_MAX_HOLD_BARS",96)
    DATA_LIMIT=_int("DATA_LIMIT",250); WATCHLIST_FILE=os.getenv("WATCHLIST_FILE","state/watchlist.json")
    STATE_FILE=os.getenv("STATE_FILE","state/bot_state.json"); JOURNAL_FILE=os.getenv("JOURNAL_FILE","logs/trades.csv")
    PAPER_SLIPPAGE_BPS=_float("PAPER_SLIPPAGE_BPS",5.0); FEE_BPS=_float("FEE_BPS",5.5)
    @classmethod
    def validate(cls):
        miss=[n for n,v in (("BITGET_API_KEY",cls.API_KEY),("BITGET_API_SECRET",cls.API_SECRET),("BITGET_API_PASSWORD",cls.API_PASSWORD)) if not v]
        if miss: raise SystemExit("Missing values in .env: "+", ".join(miss))
        if not cls.DEMO_MODE and not cls.LIVE_TRADING_ENABLED: raise SystemExit("Safety lock: DEMO_MODE=false requires LIVE_TRADING_ENABLED=true.")
        if not 0<cls.RISK_PER_TRADE_PERCENT<=2: raise SystemExit("RISK_PER_TRADE_PERCENT must be >0 and <=2.")
        if cls.MIN_RISK_REWARD<1: raise SystemExit("MIN_RISK_REWARD must be >= 1.")
